version: "3"
services:
  spovizz_app:
    container_name: ${INSTANCEID}
    restart: always
    image: h2908577.stratoserver.net:5001/spovizz/${INSTANCEID}:3.0.6
    env_file:
      - .env.prod.goldcup
networks:
  default:
    external:
      name: live_network
