# Namespace Definition
apiVersion: v1
kind: Namespace
metadata:
  name: spovizz-onefootball

---
# PersistentVolumeClaim for API data (uploads and screenshots)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-data-pvc
  namespace: spovizz-onefootball
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
# PersistentVolumeClaim for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: spovizz-onefootball
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: spovizz-onefootball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: spovizz-onefootball-cors-middleware@kubernetescrd
    spec:
      containers:
        - name: api
          image: h2908577.stratoserver.net:5001/spovizz/spovizz-api-onefootball:1.1.1
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: spovizz-api-onefootball
          volumeMounts:
            - name: api-data
              mountPath: /usr/src/app/public/upload
            - name: api-data
              mountPath: /usr/src/app/public/screenshots
          resources:
            limits:
              cpu: "6000m"
              memory: "3Gi"
      imagePullSecrets:
        - name: vigital-docker-nexus
      volumes:
        - name: api-data
          persistentVolumeClaim:
            claimName: api-data-pvc
---
# Deployment for MongoDB with Persistent Storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: spovizz-onefootball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
# Deployment for Redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: spovizz-onefootball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command: [ "redis-server", "--requirepass", "2400632bd2d976c5a16661b78dd9ek21" ]
          ports:
            - containerPort: 6379

---
# Deployment for spovizz_app (Frontend)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: spovizz-onefootball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: spovizz-onefootball-cors-middleware@kubernetescrd
    spec:
      containers:
        - name: app
          image: h2908577.stratoserver.net:5001/spovizz/spovizz-app-onefootball:1.0.4
      imagePullSecrets:
        - name: vigital-docker-nexus
---
# ClusterIssuer for Let's Encrypt to automate TLS certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: spovizz-onefootball
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adrian.szlagor@vigitalsolutions.com
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
      - http01:
          ingress:
            class: traefik
---
# Middleware for CORS
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: spovizz-onefootball-cors-middleware
  namespace: spovizz-onefootball
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
      - "DELETE"
    accessControlAllowOriginList:
      - "*"
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: websocket
  namespace: spovizz-onefootball
spec:
  plugin:
    headers:
      customRequestHeaders:
        Upgrade: websocket
      customResponseHeaders:
        Upgrade: websocket
---
# Ingress to manage external access to the services in the cluster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: spovizz-onefootball
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - api-onefootball.vigitalsolutions.com
        - onefootball.vigitalsolutions.com
      secretName: spovizz-tls
  rules:
    - host: api-onefootball.vigitalsolutions.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8080
    - host: onefootball.vigitalsolutions.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80

---
# Service for spovizz_api
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: spovizz-onefootball
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080

---
# Service for Redis
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: spovizz-onefootball
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: spovizz-onefootball
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017

---
# Service for spovizz_app (Frontend)
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: spovizz-onefootball
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: chrome-service
  namespace: spovizz-onefootball
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: websocket@kubernetescrd
spec:
  type: ClusterIP
  selector:
    app: spovizz-chrome
  ports:
    - port: 9222
      targetPort: 9222
---
# Deployment for spovizz_chrome
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spovizz-chrome
  namespace: spovizz-onefootball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spovizz-chrome
  template:
    metadata:
      labels:
        app: spovizz-chrome
    #      annotations:
    #        traefik.ingress.kubernetes.io/router.middlewares: spovizz-onefootball-cors-middleware@kubernetescrd
    spec:
      containers:
        - name: spovizz-chrome
          image: h2908577.stratoserver.net:5001/spovizz/spovizz-chrome:2.2.5
          command: [ "sh", "run.sh" ]
          env:
            - name: TZ
              value: Europe/Berlin
          resources:
            limits:
              memory: "2Gi"
              cpu: "2000m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: vigital-docker-nexus
