version: '2.4'
services:
  spovizz_chrome:
    container_name: "spovizz_chrome"
    command: [ 'sh', 'run.sh' ]
    image: h2908577.stratoserver.net:5001/spovizz/spovizz-chrome:2.3.6
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    environment:
      - TZ=Europe/Berlin
    network_mode: host
#    ports:
#     - "9222:9222"
#    cap_add:
#      - SYS_ADMIN
    shm_size: 2gb
    mem_limit: "0"
    memswap_limit: -1
    security_opt:
      - seccomp:./security-opt-chrome.json
networks:
  default:
    external:
      name: live_network
